name: Keep Actions Alive

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  keepalive:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@05456e7809058d586d96392e99217726ccc10076
        with:
          time_elapsed: 30
          use_api: false