name: Monday Backup

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 1"

jobs:
  backup:
    name: Backup
    runs-on: ubuntu-latest
    environment: FreshRSS
    defaults:
      run:
        working-directory: export-freshrss
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Tailscale
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Install dependencies
        run: npm ci

      - name: Build exporter
        run: npm run build

      - name: Export FreshRSS subscriptions
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: npm run start:prod

      - name: Archive export
        uses: actions/upload-artifact@v3
        with:
          name: export
          path: export-freshrss/export.opml
          retention-days: 7

      # Prevent the scheduled action from becoming automatically
      # disabled due to repository inactivity
      - uses: gautamkrishnar/keepalive-workflow@v1
