name: Backup Nightly
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  nightly:
    name: Backup nightly
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Hello world!"
