name: Backup Nightly
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  nightly:
    name: Backup nightly
    runs-on: ubuntu-latest
    environment: FreshRSS
    defaults:
      run:
        working-directory: export-freshrss
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build exporter
        run: npm run build

      - name: Export FreshRSS subscriptions
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: npm run start:prod

      - name: Debug
        run: ls -la

      - name: Archive export
        uses: actions/upload-artifact@v3
        working-directory: export-freshrss
        with:
          name: export.opml
          path: ./export.opml
          retention-days: 7
